spring:
  profiles:
    active: h2_spring
#    active: mysql_spring
  jpa:
    generate-ddl: true
#    show-sql: true
#    properties:
#      hibernate:
#        naming:
#          physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
