spring:
  datasource:
    url: jdbc:mysql://localhost:3306/rentalmysql?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: Sratosfera@1968
#    driver-class-name: com.mysql.cj.jdbc.Driver
